package it.uniroma1.sapy.lexer.token;

/**
 * Tipi di Token
 */
public enum Tok
{
	INTERO, STRINGA, BOOLEANO, UGUALE, MINORE, MAGGIORE, DIVERSO, MINOREUGUALE,
	MAGGIOREUGUALE, PIU, MENO, PER, DIVISO, MODULO, LEFT_PAR, RIGHT_PAR,
	DUEPUNTI, OR, AND, NOT, REM, IF, FOR, DO, THEN, ELSE, ENDIF, END, TO,
	NEXT, VARIABILE, FUNZIONE, GOTO, PRINT, INPUT, EOL
}
